rancher/hosted-providers-e2e

.github/workflows/main.yaml, Makefile, hosted/aks/support_matrix/support_matrix_importing_test.go, hosted/aks/support_matrix/support_matrix_provisioning_test.go, hosted/eks/support_matrix/support_matrix_importing_test.go, hosted/eks/support_matrix/support_matrix_provisioning_test.go, hosted/gke/support_matrix/support_matrix_importing_test.go, hosted/gke/support_matrix/support_matrix_provisioning_test.go
Successful CI run: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7052267344/job/19197055087
=> Added SupportMatrix import tests

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml, .github/workflows/main.yaml, Makefile, hosted/eks/helper/helper_cluster.go
Example workflow: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7197438632
(TODO: Parallelize the suites, coming up in next PR)
=> Refactor workflows to separate out each cloud workflow

Makefile, hosted/aks/p0/p0_importing_test.go, hosted/aks/p0/p0_provisioning_test.go, hosted/aks/p0/p0_suite_test.go, hosted/aks/support_matrix/support_matrix_suite_test.go, hosted/eks/p0/p0_importing_test.go, hosted/eks/p0/p0_provisioning_test.go, hosted/eks/p0/p0_suite_test.go, hosted/eks/support_matrix/support_matrix_suite_test.go, hosted/gke/p0/p0_importing_test.go, hosted/gke/p0/p0_provisioning_test.go, hosted/gke/p0/p0_suite_test.go, hosted/gke/support_matrix/support_matrix_suite_test.go, hosted/helpers/helper_common.go
This PR refactors P0 tests to run them in parallel in ginkgo suite and CI runs
**GitHub Actions**
AKS: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7322829508/job/19944797724
EKS: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7323099836/job/19945376823
GKE: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7323583976/job/19946357079
=> Refactor p0 tests to run in parallelized way

Makefile, README.md
This PR updates README with instructions on running tests and update Makefile with helper comments
Fixes part of #11.
=> Update README with instructions on running tests and update Makefile with helper comments

.github/scripts/generate-readme, .github/scripts/generate-tests-description, README.md, hosted/README.md
Updates ginkgo tests description and added badges
Scripts used: https://github.com/rancher-sandbox/rancher-turtles-e2e/blob/main/tests/scripts/generate-tests-description
=> Update tests description and added badge

.github/scripts/collect-rancher-logs.sh, .github/workflows/main.yaml
Collects rancher logs and store them as job artifacts
Fixes # https://github.com/rancher/hosted-providers-e2e/issues/21
https://github.com/rancher/hosted-providers-e2e/actions/runs/7418899987
=> Collect logs artifacts

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
This reverts commit 7565240bdec2617c2045c9452527460fbcc44dd5.
Fixes #
=> Revert "Changes to GKE and see if it works"

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
Fixes #28 
1. [GKE Job](https://github.com/valaparthvi/hosted-providers-e2e/actions/runs/7499570480/job/20416608591) has failed but at least we do not see issue with input variable. It has taken the value of instance template.
=> Fix Cron Job Scheduler to use inputs

.github/workflows/main.yaml
Current scheduler does not run any tests because the comparable is not correct. This PR attempts at fixing the issue.
Fixes #
=> Fix scheduled gh action to run the tests

.github/workflows/main.yaml
This PR fixes the Azure action issue https://github.com/Azure/login/issues/403 by version pinning the azure to last working version i.e. v1.5.1.
Fixes #
=> Version pin azure github action

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml, .github/workflows/main.yaml
Fixes inputs for manual trigger and scheduled jobs
Manual job: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7581226606
Scheduled job: https://github.com/cpinjani/hosted-providers-e2e/actions/runs/7582477410/job/20652154509
The jobs ran above are only tested for provisioning tests (as importing tests are TBF in https://github.com/rancher/hosted-providers-e2e/pull/39) and final commit has the desired values set to run nightly runs
=> Fix scheduled job inputs

.github/workflows/aks.yaml, cattle-config-provisioning.yaml, hosted/helpers/helper_common.go
Fixes failing CI: https://github.com/rancher/hosted-providers-e2e/actions/runs/7983942169/job/21799970048#step:15:67
https://github.com/rancher/hosted-providers-e2e/actions/runs/7986518138
=> AKS k8s version bump

hosted/aks/helper/helper_cluster.go, hosted/aks/k8s_chart_support/k8s_chart_support_import_test.go, hosted/aks/k8s_chart_support/k8s_chart_support_provisioning_test.go, hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/eks/helper/helper_cluster.go, hosted/eks/k8s_chart_support/k8s_chart_support_import_test.go, hosted/eks/k8s_chart_support/k8s_chart_support_provisioning_test.go, hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/helpers/helper_rancher.go, hosted/helpers/structs.go
This PR automates chart support upgrade tests for AKS and EKS.
Fixes part of #49
=> Automate chart support upgrade scenarios for AKS and EKS 

.github/workflows/janitor.yaml, hosted/eks/helper/helper_cluster.go, hosted/helpers/structs.go
Setup nightly workflow for stale cluster cleanups
Fixes #68 
https://github.com/cpinjani/hosted-providers-e2e/actions/runs/8346989806
- aws-janitor is waiting on an initial release of https://github.com/rancher-sandbox/aws-janitor, which will be created after https://github.com/rancher-sandbox/aws-janitor/pull/4.
- Downstream clusters which were not marked for cleanup in workflows will be ignored (filtered using username)
=> Setup Resources Cleanup

.github/workflows/janitor.yaml
Enable aws-janitor since its released
=> Enable aws-janitor

hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/aks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/aks/p0/p0_suite_test.go, hosted/aks/support_matrix/support_matrix_suite_test.go, hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/eks/p0/p0_suite_test.go, hosted/eks/support_matrix/support_matrix_suite_test.go, hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/gke/p0/p0_suite_test.go, hosted/gke/p1/p1_suite_test.go, hosted/gke/support_matrix/support_matrix_suite_test.go, hosted/helpers/helper_common.go
Fixes #104 
**GKE**:
1. p0 - https://github.com/rancher/hosted-providers-e2e/actions/runs/9021501065
2. k8s-chart-support - https://github.com/rancher/hosted-providers-e2e/actions/runs/9031520944/job/24817946163
3. p1 - https://github.com/rancher/hosted-providers-e2e/actions/runs/9030533426/job/24815038300
4. support-matrix - https://github.com/rancher/hosted-providers-e2e/actions/runs/9032127922
**AKS:**
1. p0 -https://github.com/rancher/hosted-providers-e2e/actions/runs/9030497848
2. k8s-chart-support - https://github.com/rancher/hosted-providers-e2e/actions/runs/9031516845/job/24817933517
3. support-matrix - https://github.com/rancher/hosted-providers-e2e/actions/runs/9031908156
**EKS:**
1. p0 - https://github.com/rancher/hosted-providers-e2e/actions/runs/9021600351
2. …
=> Add SynchronizedBeforeSuite to avoid panic and race condition with config file

hosted/aks/helper/helper_cluster.go, hosted/eks/helper/helper_cluster.go, hosted/eks/k8s_chart_support/k8s_chart_support_import_test.go, hosted/eks/k8s_chart_support/k8s_chart_support_provisioning_test.go, hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_import_upgrade_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/eks/p0/p0_importing_test.go, hosted/eks/p0/p0_provisioning_test.go, hosted/eks/p0/p0_suite_test.go, hosted/eks/support_matrix/support_matrix_importing_test.go, hosted/eks/support_matrix/support_matrix_provisioning_test.go, hosted/eks/support_matrix/support_matrix_suite_test.go, hosted/helpers/helper_common.go
- Refactors EKS tests
- Fixes EKS k8s version range
- Use gomega for err checks
- Reposition helper functions
Fixes #99 
ASK P0: https://github.com/rancher/hosted-providers-e2e/actions/runs/9250244678
EKS P0: https://github.com/rancher/hosted-providers-e2e/actions/runs/9258037848
EKS SupportMatrix, K8S Chart Support: https://github.com/rancher/hosted-providers-e2e/actions/runs/9234566090
v2.8-head is failing, so tested on v2.8.4
=> Refactor EKS tests

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml, .github/workflows/main.yaml
See what tests are run in the GH summary.
Fixes #
=> Add tests_to_run to github summary

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml, .github/workflows/janitor.yaml
Disable scheduled jobs for release/v2.8
=> Disable scheduled jobs

Makefile, hosted/gke/helper/helper_cluster.go
This PR fixes panic with autoscaling tests.
Fixes #
=> Fix panic with autoscaling import tests

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml, .github/workflows/main.yaml
Bumping GCP template to openSUSE 15.6
Fixes #50 
Without setting `CGO_LDFLAGS` containing `-lresolv` it was failing on:
=> Bump GCP template to openSUSE 15.6

.github/workflows/main.yaml
Cherry-pick of https://github.com/rancher/hosted-providers-e2e/pull/126 for 2.8 branch
=> Use gcloud for getting IP

hosted/gke/helper/helper_cluster.go, hosted/gke/p1/p1_provisioning_test.go, hosted/helpers/helper_common.go
This PR automates Qase 25,26 and 30.
Fixes #
=> GKE: Automate Qase 25, and 26

hosted/gke/p1/p1_import_test.go, hosted/gke/p1/p1_provisioning_test.go, hosted/gke/p1/p1_suite_test.go
=> Automate Qase: 31, 33, and 56

.github/workflows/eks.yaml, cattle-config-provisioning.yaml, hosted/eks/helper/helper_cluster.go, hosted/eks/k8s_chart_support/k8s_chart_support_provisioning_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go, hosted/eks/p0/p0_provisioning_test.go, hosted/eks/p1/p1_provisioning_test.go, hosted/eks/p1/p1_suite_test.go, hosted/eks/support_matrix/support_matrix_provisioning_test.go
Adds automation for above EKS P1 Provisioning test cases.
:green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10195897050
=> EKS - Automate Qase: 126, 141 and 255

.github/scripts/collect-rancher-logs.sh, .github/workflows/main.yaml
This PR adds crust-gather to CI so that logs can be explored better.
This is still experimental so the rancher-log-collector has not been removed.
Fixes #125
=> Add crust-gather to CI for log collection

.github/workflows/main.yaml
Cherry-pick of PR https://github.com/rancher/hosted-providers-e2e/pull/136
https://github.com/rancher/hosted-providers-e2e/actions/runs/10844646156
=> v2.8 - AZ CLI Removal

hosted/aks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go, hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
This PR fixes k8s chart support upgrade tests ~and adds GH action workflow file~.
These tests were originally written to test k8s upgrade with a new chart release, but since it involves upgrading Rancher, it can be used to test Rancher upgrade and ensure things work even after the upgrade.
Fixes #
=> Fix K8s/Rancher upgrade tests

cattle-config-provisioning.yaml, hosted/gke/p1/p1_import_test.go, hosted/gke/p1/p1_provisioning_test.go, hosted/gke/p1/p1_suite_test.go, hosted/helpers/helper_common.go
- Adds GKE Private cluster tests and Qase ID 5
- Changes network to run GKE tests
Fixes #173 
p0_provisioning/p0_import/p1_provisioning[focused run] - https://github.com/rancher/hosted-providers-e2e/actions/runs/11158426674
=> GKE Private cluster tests

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
Modifies current scheduled jobs and adds weekly run for P1/Sync tests.
Tested the syntax changes in my forked repo.
=> Add weekly schedule run for P1 tests

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
Fixes problem with crust-gather logging 
Fixes https://github.com/crust-gather/crust-gather/issues/155
=> Bump kubernetes version to fix crust-gather collect

hosted/gke/helper/helper_cluster.go, hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go, hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go, hosted/gke/p0/p0_import_test.go, hosted/gke/p0/p0_provisioning_test.go, hosted/gke/p0/p0_suite_test.go, hosted/gke/p1/p1_import_test.go, hosted/gke/p1/p1_provisioning_test.go, hosted/gke/p1/p1_suite_test.go, hosted/gke/p1/sync_provisioning_test.go, hosted/gke/support_matrix/support_matrix_provisioning_test.go, hosted/helpers/helper_common.go
- Adds provisioning tests for GKE Regional cluster to P0 suite
- Adds UpgradeNodeKubernetesVersion function
- Adds new tests for Cluster/Nodepool concurrent upgrade
https://github.com/rancher/hosted-providers-e2e/actions/runs/11427687470/job/31792094822
=> Added GKE Regional cluster tests

.github/workflows/janitor.yaml
Move from rancher-sandbox/aws-janitor to rancher/aws-janitor
Fixes - Failing job https://github.com/rancher/hosted-providers-e2e/actions/runs/11452609839
Fixed job: https://github.com/rancher/hosted-providers-e2e/actions/runs/11454419292
=> Update aws-janitor repo

hosted/aks/helper/helper_cluster.go, hosted/aks/p1/p1_import_test.go, hosted/aks/p1/p1_provisioning_test.go, hosted/aks/p1/p1_suite_test.go, hosted/aks/p1/sync_import_test.go, hosted/aks/p1/sync_provisioning_test.go, hosted/eks/p1/sync_importing_test.go
- Automate sync from azure cloud console: 302, 233
- Automate invalid CC update: 299, 238
Fixes #
=> Automate Qase 302, 233, 299, and 238

.github/workflows/main.yaml, cattle-config-provisioning.yaml, hosted/aks/helper/helper_cluster.go, hosted/aks/p1/p1_provisioning_test.go
Automate Qase 210, 211, 212, 213 - Test various Network plugin and policy combinations.
Fixes #
=> Automate Qase 210, 211, 212, 213 

hosted/eks/helper/helper_cluster.go, hosted/eks/p1/p1_import_test.go, hosted/eks/p1/p1_provisioning_test.go, hosted/eks/p1/p1_suite_test.go, hosted/helpers/helper_common.go
=> Automate Qase 274, 94, 97, 99, 143, 145, 107, 105

.github/workflows/release-matrix.yaml
I'd like to test all operators at once
=> Release matrix testing all operators at once

hosted/aks/helper/helper_cluster.go, hosted/aks/p1/p1_provisioning_test.go, hosted/helpers/structs.go
=> AKS: Automate Qase 240, 196

.github/dependabot.yml
This PR groups both `github.com/onsi` packages i.e. ginkgo and gomega.
Fixes #
=> Group github.com/onsi deps

go.mod, go.sum, hosted/eks/p1/p1_suite_test.go, hosted/helpers/helper_common.go
- This PR removes rancher/norman dependency which can be avoided by defining our local copy of the function.
Fixes #
This PR does not have any GH action since the test is currently blocker and marked pending.
=> Remove single use dependency rancher/norman

hosted/aks/helper/helper_cluster.go, hosted/aks/p1/p1_import_test.go, hosted/aks/p1/p1_provisioning_test.go, hosted/aks/p1/p1_suite_test.go
=> Automate Qase 223 and 303, AKS: update cluster when in updating state

.github/workflows/main.yaml, hosted/eks/p1/p1_provisioning_test.go
=> Automate Qase 149

.github/workflows/main.yaml, .github/workflows/release-matrix.yaml, Makefile, hosted/aks/backup_restore/backup_restore_import_test.go, hosted/aks/backup_restore/backup_restore_provisioning_test.go, hosted/aks/backup_restore/backup_restore_suite_test.go, hosted/eks/backup_restore/backup_restore_import_test.go, hosted/eks/backup_restore/backup_restore_provisioning_test.go, hosted/eks/backup_restore/backup_restore_suite_test.go, hosted/gke/backup_restore/backup_restore_import_test.go, hosted/gke/backup_restore/backup_restore_provisioning_test.go, hosted/gke/backup_restore/backup_restore_suite_test.go, hosted/helpers/helper_backup.go
Adds Backup/Restore tests for imported clusters
Fixes #237 
https://github.com/rancher/hosted-providers-e2e/actions/runs/13011578842
=> BackupRestore Imported clusters tests

README.md, docs/release-testing.md
This PR adds a doc that QA can refer to know what tests to run when release testing.
Fixes #
=> Add doc for release testing

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #
Checklist:
=> update cronjob timing

.github/workflows/aks.yaml, .github/workflows/eks.yaml, .github/workflows/gke.yaml
**After last update to change the cronjob timing, the tests stopped running. This PR fixes that.**
=> fix cronjob to run tests

README.md, cattle-config-import.yaml, cattle-config-provisioning.yaml, hosted/helpers/helper_common.go
=> update region in cattle config

.github/workflows/main.yaml
This PR updates the GCP Runner region.
Fixes #
=> update gcp runner region
