rancher/hosted-providers-e2e

- .github/workflows/main.yaml
The common runner image modified the configure-gh-runner.sh script that now expects some env variables. This PR updates the workflow to prepare those env vars and make them available for use.
> Update workflow to work with the common script

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
[GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7356019159)
[EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7356018018)
[AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7356016741)
All the above runs were triggered simultaneously, EKS-E2E failed.
Things that can be improved here is:
1. None of the 4 test steps must be dependent on each other, if one fails the others should continue to run.
2. The possibility to run all the 4 tests in parallel.
> Fix GitHub actions

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- Makefile
Added an option to run tests on operator nightly charts (default true)
With nightly chart - https://github.com/rancher/hosted-providers-e2e/actions/runs/7385110621/job/20089259358
Without nightly chart - https://github.com/rancher/hosted-providers-e2e/actions/runs/7385864856/job/20091431266
> Use operator nightly charts for CI run

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- README.md
- cattle-config-import.yaml
- cattle-config-provisioning.yaml
- hosted/aks/p0/p0_importing_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/support_matrix/support_matrix_importing_test.go
- hosted/aks/support_matrix/support_matrix_suite_test.go
- hosted/eks/p0/p0_importing_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/support_matrix/support_matrix_importing_test.go
- hosted/eks/support_matrix/support_matrix_suite_test.go
- hosted/gke/p0/p0_importing_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/support_matrix/support_matrix_importing_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_suite_test.go
- hosted/helpers/helper_common.go
This PR adds GCP Zone for running runner in the hosted providers workflow templates so that it is easier to test geolocalized templates and have an option to instantiate the runner in any other region.
Fixes #
~1. https://github.com/rancher/hosted-providers-e2e/actions/runs/7395629941/job/20119191235~
~2. [EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7395954958)~
~3. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7395952783)~
1. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7446950908)
2. [EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7446949481)
3. [AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7446947195)
> Update all the workflow input with GCP Zone and move to geolocalized instance template

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
This PR reverses some of the changes that were made in the previous commits.
Fixes #
> Fix issue with GH Action Input

- hosted/aks/helper/helper_cluster.go
- hosted/eks/helper/helper_cluster.go
- hosted/gke/helper/helper_cluster.go
- hosted/helpers/helper_common.go
This PR fixes issues introduced in PR #19, one of which was the inability to create AKS cluster where it failed to read the nodecount.
Fixes #
Verified this locally, the aks cluster is created.
> Fix AKS cluster config issue

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- hosted/helpers/helper_common.go
This PR fixes:
1. Scheduled GH actions not taking appropriate inputs.
2. Invalid aksClusterConfig key introduced in https://github.com/rancher/hosted-providers-e2e/pull/19.
Fixes #
1. [GKE](https://github.com/valaparthvi/hosted-providers-e2e/actions/runs/7551614167/job/20559116337)
2. [EKS](https://github.com/valaparthvi/hosted-providers-e2e/actions/runs/7552017891/job/20560178134)
> Fix the scheduled actions to take correct input and fix invalid aksClusterConfig key

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p0/p0_importing_test.go
- hosted/aks/p0/p0_provisioning_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/support_matrix/support_matrix_importing_test.go
- hosted/aks/support_matrix/support_matrix_provisioning_test.go
- hosted/eks/helper/helper_cluster.go
- hosted/eks/p0/p0_importing_test.go
- hosted/eks/p0/p0_provisioning_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/support_matrix/support_matrix_importing_test.go
- hosted/eks/support_matrix/support_matrix_provisioning_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p0/p0_importing_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/support_matrix/support_matrix_importing_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_suite_test.go
- hosted/helpers/helper_common.go
This PR:
1. Fixes bugs introduced in #19 
2. Add `owner` and `testfilenumber` labels identify the cluster resource.
Fixes #
1. [EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7572765051)
4. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7570080256)
5. [AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7570077586)
> Fix bugs introduced in geolocalization PR and add labels

- .github/workflows/main.yaml
1. Update GH actions: google-github-actions/auth, google-github-actions/setup-gcloud to v2 to fix warnings related to nodejs16.
2. Update GH action: azure/login to v1 since https://github.com/Azure/login/issues/403 has been fixed.
Fixes #45 
1. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7709027588)
2. [GKE-E2E-2](https://github.com/rancher/hosted-providers-e2e/actions/runs/7710091749)
3. [GKE-E2E-3](https://github.com/rancher/hosted-providers-e2e/actions/runs/7722722175) - this job has failed but there are no Node.js 16 warnings from any actions except azure/login (see: https://github.com/Azure/login/issues/413)
> Update GH action plugins to fix Node.js 16 deprecation warnings

- cattle-config-import.yaml
- cattle-config-provisioning.yaml
- hosted/gke/p0/p0_suite_test.go
This PR fixes GKE tests failing due to unavailable version. Currently we use `1.27.4-gke.900` which has become unavailable.
Excerpt of gke-operator pod logs:
```yaml
time="2024-01-31T07:51:01Z" level=error msg="error syncing 'cattle-global-data/c-hgflj': handler gke-controller: googleapi: Error 400: Master version \"1.27.4-gke.900\" is unsupported.\nDetails:\n[\n  {\n    \"@type\": \"type.googleapis.com/google.rpc.RequestInfo\",\n    \"requestId\": \"0x80de9c07e8bffe0a\"\n  }\n]\n, badRequest, requeuing"
```
Failing Action: https://github.com/rancher/hosted-providers-e2e/actions/runs/7721123412/job/21047171556
Fixes #
1. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7723967956)
> Use default k8s version provided by GKE

- hosted/eks/helper/helper_cluster.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p0/p0_importing_test.go
- hosted/gke/support_matrix/support_matrix_importing_test.go
This PR attempts to fix GKE and EKS not getting deleted on user interrupt.
This PR also adds a `--project` flag to GKE deletion, this ensures when running the test locally with a multi project setup, correct project is used.
I faced this issue locally, where my `gcloud` was configured to use project-2, but since my test config used `project-1`, the test created GKE on `project-1`. While deleting GKE, the `gcloud` used `project-2` because we did not explicitly pass a project, and since it did not find the resource to delete, the test failed.
Fixes #
1. [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7639263489)
> Fix Imported GKE and EKS not getting deleted on user interrupt

- .github/workflows/main.yaml
- Makefile
- cattle-config-provisioning.yaml
- hosted/helpers/helper_common.go
This implements to run tests independent of each other
Fixes # https://github.com/rancher/hosted-providers-e2e/issues/16
https://github.com/rancher/hosted-providers-e2e/actions/runs/7797757146
> Improve GHA tests steps

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- hosted/gke/helper/helper_cluster.go
1. Fix GKE tests that failed when upgrading from one major version to another, for e.g v1.26.8-gke.200 -> v1.27.3-gke.100. Ref: [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7812352834/job/21309263401)
```
time="2024-02-07T09:58:19Z" level=info msg="ClusterID: c-dwrfx, Message: [googleapi: Error 400: Node version \"1.27.3-gke.100\" must not have a greater minor version than master version \"1.26.8-gke.200\".\nDetails:\n[\n  ***\n    \"@type\": \"type.googleapis.com/google.rpc.RequestInfo\",\n    \"requestId\": \"0xe424a128d6e3269e\"\n  ***\n]\n, badRequest], Error: true, State: updating, Transitioning: false"
```
2. Add custom workflow run-name to all the workflows to easily identify which downstream, rancher and upstream versions were using for a specific run …
> Fix GKE tests when upgrading a major version and add custom workflow run-name to all the workflows

- .github/dependabot.yml
This change will only do patch updates. For e.g. updating v0.27.9 -> v0.27.10.
Fixes #
> Update dependabot.yml to ignore k8s.io related pkgs

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- hosted/helpers/helper_common.go
- Adds support in framework to run tests on any available Rancher manager
- Changed job summary, as custom run-name was not working on scheduled jobs
Fixes #62 
Custom Rancher: 
[AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7885120818) [EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7886952272) [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7886292072)
CI Installed Rancher: 
[AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7885883472) [EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7886956678) [GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/7886294089)
Since GHA has limitation of max 10 inputs for workflow_dispatch, disabled _k3s_version_ input as a …
> Add ability to run tests on available Rancher Manager

- Makefile
Re-add --version to rancher helm installation command. If this is not passed, the latest version is taken which I am not sure is correct. So if we want to test `v2.7-head` and we provide `--set rancherImageTag=v2.7.11-head` but no `--version=v2.7.10`, then `v2.8.2` is used which does not seem right.
Fixes #
```
helm install rancher rancher-latest/rancher --namespace cattle-system --set rancherImageTag=v2.7.11-head --set hostname=<hostname> --set global.cattle.psp.enabled=false --set bootstrapPassword=adminadmin --create-namespace --wait
```
1. Navigate to local cluster --> Apps --> Installed Apps
2. Check the Rancher version
> Re-add --version to rancher helm installation command

- .github/workflows/main.yaml
- Makefile
- go.mod
- go.sum
- hosted/aks/p0/p0_importing_test.go
- hosted/aks/p0/p0_provisioning_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/support_matrix/support_matrix_importing_test.go
- hosted/aks/support_matrix/support_matrix_provisioning_test.go
- hosted/aks/support_matrix/support_matrix_suite_test.go
- hosted/eks/p0/p0_importing_test.go
- hosted/eks/p0/p0_provisioning_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/support_matrix/support_matrix_importing_test.go
- hosted/eks/support_matrix/support_matrix_provisioning_test.go
- hosted/eks/support_matrix/support_matrix_suite_test.go
- hosted/gke/p0/p0_importing_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/support_matrix/support_matrix_importing_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_suite_test.go
- hosted/helpers/qase/helper_qase.go
Integrates QASE test management tool reporting with tests.
Fixes #31 
[AKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/8076073615) QASE Report: https://app.qase.io/run/HIGHLANDER/dashboard/38
[GKE-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/8076340794) QASE Report: https://app.qase.io/run/HIGHLANDER/dashboard/39
[EKS-E2E](https://github.com/rancher/hosted-providers-e2e/actions/runs/8077356363) QASE Report: https://app.qase.io/run/HIGHLANDER/dashboard/42
- Delete Test Run functionality is working, but Test run not deled due to QASE insufficient permissions
- Most of the code is referenced from Elemental implementation: https://github.com/rancher/elemental/pull/1176
> QASE Integration

- Makefile
- README.md
- go.mod
- go.sum
- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/helpers/helper_common.go
- hosted/helpers/helper_rancher.go
- hosted/helpers/structs.go
This PR adds tests for k8s chart support test for GKE.
Fixes part of #49 
Env Vars to use:
```
CATTLE_TEST_CONFIG=github.com/rancher/hosted-providers-e2e/cattle-config-import.yaml
GCP_CREDENTIALS=<gcp_creds>
GKE_PROJECT_ID=<gcp-project>
GKE_ZONE=us-central1-c
KUBECONFIG=/etc/k3s/k3s.yaml
K8S_UPGRADE_MINOR_VERSION=1.28
PROVIDER=gke
RANCHER_HOSTNAME=hostname
RANCHER_PASSWORD=adminadmin
RANCHER_UPGRADE_VERSION=devel/2.8
RANCHER_VERSION=2.8.2
```
> Add K8s chart support tests for GKE

- README.md
- hosted/aks/helper/helper_cluster.go
- hosted/aks/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/aks/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/support_matrix/support_matrix_importing_test.go
- hosted/aks/support_matrix/support_matrix_provisioning_test.go
- hosted/aks/support_matrix/support_matrix_suite_test.go
- hosted/eks/helper/helper_cluster.go
- hosted/eks/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/eks/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/support_matrix/support_matrix_importing_test.go
- hosted/eks/support_matrix/support_matrix_provisioning_test.go
- hosted/eks/support_matrix/support_matrix_suite_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/support_matrix/support_matrix_importing_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_suite_test.go
- hosted/helpers/helper_common.go
This PR makes the following change:
1. Add Qase IDs to K8s Chart Support tests.
2. Cleanup code for GKE Chart support tests to use global variables for fetching rancher and k8s version instead.
3. Add cluster specific `GetK8sVersion` to use DOWNSTREAM_KUBERNETES_VERSION or `Default[EKS/AKS/GKE]` to fetch the k8s version.
Fixes #52
> Add Qase IDs for K8s Chart Support tests and cleanup code

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- hosted/gke/p0/p0_other_provisioning_test.go
1. Automate Invalid GKE config tests
2. Update eks/aks/gke.yaml GH Action to use the default UI K8s version for scheduled jobs
Fixes #
> Automate Invalid GKE config tests and update eks/aks/gke.yaml GH Action to use the default UI K8s version for scheduled jobs

- hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/support_matrix/support_matrix_suite_test.go
- hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/support_matrix/support_matrix_suite_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/support_matrix/support_matrix_suite_test.go
- hosted/helpers/helper_common.go
Remove the unnecessary `err` returned during `CommonBeforeSuite`.
Fixes #
> Cleanup CommonBeforeSuite

- hosted/aks/helper/helper_cluster.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/gke/p0/p0_importing_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/p1/p1_suite_test.go
1. Add `wait` and `checkClusterConfig` to helper_cluster.go functions.
Fixes #
Support Matrix Nightly: https://github.com/rancher/hosted-providers-e2e/actions/runs/9223675757/job/25377400776
Support Matrix (Provisioning :red_circle:): https://github.com/rancher/hosted-providers-e2e/actions/runs/9223652931/job/25377328302
P0 Nightly: https://github.com/rancher/hosted-providers-e2e/actions/runs/9223666989/job/25377374496
P0: https://github.com/rancher/hosted-providers-e2e/actions/runs/9223327019/job/25376294278
P1 ( :red_circle:) : https://github.com/rancher/hosted-providers-e2e/actions/runs/9223672372/job/25377389192
> Refactor GKE

- hosted/aks/helper/helper_cluster.go
- hosted/eks/helper/helper_cluster.go
- hosted/eks/p0/p0_suite_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p0/p0_suite_test.go
Fixes issue where _ui-k8s-default-version-range_ is updated, but operator not yet supports that k8s version
For eg. ui-k8s-default-version-range <=v1.30.x", operator highest supported version <=1.29
Fixes:
- Part of https://github.com/rancher/hosted-providers-e2e/issues/117
- Failing CI P0 jobs
[AKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9546464074), [EKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9550218118), [GKE](https://github.com/rancher/hosted-providers-e2e/actions/runs/9550649412)
> Fix default k8s version used for tests

- hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/helpers/helper_rancher.go
Adds a check to ensure Rancher API is available after chart is re-installed to latest version
Fixes #117 
[AKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9567909734), [EKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/9576500166), [GKE](https://github.com/rancher/hosted-providers-e2e/actions/runs/9565279217)
> Fix for chart support tests

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
followup for https://github.com/rancher/hosted-providers-e2e/pull/123
Bumping GCP template to openSUSE 15.6 on `release/v2.8 branch`
Testrun for GKE p0_provisioning here https://github.com/rancher/hosted-providers-e2e/actions/runs/9792091101
> Use new GCP template based on openSUSE 15.6

- .github/workflows/main.yaml
Changes method to use gcloud instead of an external service to get runner IP
https://github.com/rancher/hosted-providers-e2e/actions/runs/9794227828
> Use gcloud for runner IP

- cattle-config-provisioning.yaml
- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/p1_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
1. Add `npSize` to CreateGKEHostedCluster to create nodepool with more than 1 np.
2. Add `AddNodePoolOnGCloud` to add nodepool via CLI.
3. Automate qase 55 and 34 - changing non-windows > windows should fail
4. Automate all windows np should fail.
Fixes #
> Automate Qase 55 and 34; Windows nodepool update in GKE

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- Makefile
- README.md
- hosted/README.md
- hosted/aks/p0/p0_import_test.go
- hosted/aks/support_matrix/support_matrix_import_test.go
- hosted/eks/p0/p0_import_test.go
- hosted/eks/support_matrix/support_matrix_import_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p0/p0_import_test.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/sync_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_import_test.go
- Rename _importing_ references to _import_ to match with _cattle-config-**import**.yaml_ and use uniformly 
- Fix GKE P1 tests
> Rename importing references

- hosted/gke/helper/helper_cluster.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/p1_provisioning_test.go
- hosted/gke/p1/p1_suite_test.go
- Automate update a cluster when it is updating state.
Fixes #
> Automate Qase 265 and 35; Update a cluster when in updating state

- .github/workflows/main.yaml
Removes AZ CLI installation code as it already seemed installed on the latest runner template, and zypper upgrade for the package errors out.
Fixes - Failing CI https://github.com/rancher/hosted-providers-e2e/actions/runs/10173991179/job/28139007477
https://github.com/rancher/hosted-providers-e2e/actions/runs/10175208035/job/28142257485
> AZ CLI Removal

- hosted/aks/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/aks/k8s_chart_support/upgrade/k8s_chart_support_import_upgrade_test.go
- hosted/aks/p0/p0_import_test.go
- hosted/eks/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_import_upgrade_test.go
- hosted/eks/p0/p0_import_test.go
- hosted/gke/k8s_chart_support/k8s_chart_support_import_test.go
- hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_import_upgrade_test.go
- hosted/gke/p0/p0_import_test.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/sync_import_test.go
- hosted/helpers/helper_common.go
Instead of writing the workaround for every test, move the workaround to WaitUntilClusterIsReady().
Fixes #
> Move workaround for imported clusters to WaitUntilClusterIsReady

- .github/workflows/aks.yaml
- hosted/aks/helper/helper_cluster.go
- hosted/aks/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/aks/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go
- hosted/aks/p0/p0_provisioning_test.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- hosted/aks/support_matrix/support_matrix_provisioning_test.go
Automate:
1. Create cluster with 0 nodecount
2. Create cluster with 0 nodepool
3. Test autoscaling on provisioned/imported
4. Add `updateFunc` arg to CreateAKSHostedCluster so that cluster config can be modified as per the test requirement.
5. Update all the tests to accommodate the new `updateFunc` addition.
Fixes #
> Automate Qase: 176, 186, 187 and 266

- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_provisioning_test.go
- hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_provisioning_upgrade_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p1/p1_provisioning_test.go
- hosted/gke/p1/sync_provisioning_test.go
- hosted/gke/support_matrix/support_matrix_provisioning_test.go
- Add `updateFunc` arg to `CreateGKEHostedCluster` so that cluster config can be modified as per the test requirement.
- Remove `npSize` from the function.
Fixes #
> Add updateFunc arg to GKE create method

- hosted/eks/helper/helper_cluster.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/helpers/helper_common.go
Adds automation for EKS P1 Provisioning tests, Qase IDs - 120, 146, 147, 125, 148, 128, 131, 144, and 142
:green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10217897213
> EKS P1Provisioning

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p1/p1_provisioning_test.go
Automate:
- 218: Delete the cluster while cluster is in creation state
- 219: Re-create a cluster while its in deletion state
- 182: User should not be able to select Nodepool k8s version during creation
- Fix GKE tests to use cluster.Transitioning and cluster.TransitioningMessage instead of conditions.
Fixes #
> Automate Qase:  218, 182, and 219

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- hosted/gke/helper/helper_cluster.go
- 183, 269 : NP cannot be upgraded to k8s version greater than CP k8s version
- 189: A cluster with multiple nodepools should be created
- 190, 268: should to able to delete a nodepool and add a new one
- 191, 267: should not be able to remove system nodepool
- Add new helper functions: UpdateCluster, AddNodePoolOnAzure
- Update `UpdateCluster` for GKE and AKS
Fixes #
> Automate Qase: 183, 189, 190, 191, 267, 268, 269

- .github/workflows/eks.yaml
- hosted/eks/helper/helper_cluster.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/eks/p1/sync_importing_test.go
- hosted/eks/p1/sync_provisioning_test.go
- Automates and adds EKS Sync TCs to P1 suite, Qase IDs: 112, 114, 157 and 159
- Fixes flaky check of function _UpgradeNodeKubernetesVersion_
P0: :green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10266613984
SyncImport/SyncProvisioning: :green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10282588336
> EKS Sync automation

- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- 205 - should be able to create a cluster with empty tag
- 193 - should successfully create cluster with multiple nodepools in multiple AZs
- 177, 270 - should be able to update tags
Fixes #
> Automate Qase: 177, 270, 205, 193

- Makefile
- hosted/eks/helper/helper_cluster.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/eks/p1/sync_importing_test.go
- hosted/helpers/helper_common.go
- Adds automation for EKS P1 import tests
- Refactors common P1 functions
- Add tag _aws-janitor=marked-for-deletion_ to cleanup EKS cluster on janitor next run, instead of next+1 run
P1Provisioning - :green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10441389153
P1Import- :green_circle: https://github.com/rancher/hosted-providers-e2e/actions/runs/10454461150
> EKS P1Import tests

- hosted/helpers/helper_common.go
This PR fixes GH action failure due to the newly added aws-janitor tag.
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=Invalid field 'resource_labels.key': "aws-janitor/marked-for-deletion". It must only contain lowercase letters ([a-z]), numeric characters ([0-9]), underscores (_) and dashes (-), and must start with a letter. International characters are allowed.
```
```
\nRESPONSE 400: 400 Bad Request\nERROR CODE: InvalidTagNameCharacters\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"InvalidTagNameCharacters\",\n    \"message\": \"The tag names 'aws-janitor/marked-for-deletion' have reserved characters '<,>,%,&,\\\\,?,/' or control characters. These characters are only allowed for …
```
> Fix GKE and AKS failure due to aws-janitor tag

- .github/scripts/collect-rancher-logs.sh
- .github/scripts/squid.conf
- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- Makefile
This PRs adds steps to install rancher behind proxy for automation tests using [Squid proxy](https://www.squid-cache.org/). 
Fixes #128 
These changes are copied from/implemented using rancher/elemental CI. Check the logs to know if requests went through proxy.
TODO: Add a doc to setup Rancher behind proxy.
> [CI]: Setup Rancher behind proxy in CI

- hosted/eks/helper/helper_cluster.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/eks/p1/sync_importing_test.go
1. Modify `DeleteEKSClusterOnAWS` to list all the nodegroups and delete them before deleting the cluster.
2. Rename `eks_region` to `region` to conform with the Go naming convention that says 'Names in Go should in general not contain underscores'.
3. Fix EKS cluster not cleaned up for "reimport an existing cluster".
<details><summary>Details</summary>
```
• [842.949 seconds]
P1Import when a cluster is imported Reimporting/Editing a cluster with invalid config Reimport a cluster to Rancher should fail
/home/gh-runner/actions-runner/_work/hosted-providers-e2e/hosted-providers-e2e/hosted/eks/p1/p1_import_test.go:146
Captured StdOut/StdErr Output >>
Creating EKS cluster ...
Running command: eksctl [create cluster --region=*** --name=auto-eks-hp-ci-qvvaw --version=1.30 --nodegroup-name …
```
> Fix EKS cleanup on a new nodegroup addition for imported clusters

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/support_matrix/support_matrix_suite_test.go
- hosted/eks/helper/helper_cluster.go
- hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/helpers/helper_common.go
1. Simplify `GetK8sVersion` for all the hosted providers to call list single variants of each minor version and return a version based on `forUpgrade` parameter.
2. Rename AKS `ListSingleVariantAKSAvailableVersions` to `ListSingleVariantAKSAllVersions`, also modify it to return the versions in descending order 1.28.3, 1.28.0, etc, and modify the tests using this function with required changes.
Fixes #147
1. GKE P1 on 2.9-head uses 1.30.3-gke.1969000 - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575523066/job/29299429366
2. GKE P0 on 2.8-head uses 1.27.16-gke.1234000 (upgrade=true), and 1.28.13-gke.1006000 (upgrade=false) - https://github.com/rancher/hosted-providers-e2e/actions/runs/10575520397/job/29299407442
3. GKE Sync on 2.8-head - …
> Fix GetK8sVersion for all the hosted providers

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
199: Create cluster - "Container monitoring" Enabled
200, 201, 271: Update the cluster - Enable monitoring, The user should be able to disable monitoring once enabled
203: Create cluster - Nodepool with Max pods per node 9
237: Register cluster with no RBAC
Fixes #
> Automate Qase: 199, 200, 203, 237, 271

- hosted/aks/p1/p1_suite_test.go
Re-enable disable monitoring test since aks-operator/issues/584 is fixed
Nightly chart: https://github.com/rancher/hosted-providers-e2e/actions/runs/10790181438
Regular chart: https://github.com/rancher/hosted-providers-e2e/actions/runs/10790188853
(failing test not related to the change, will check it locally)
> Enable AKS Monitoring Test

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
This PR automates AKS P1 provisioning and import test cases.
It also un-XIt's 199 now that r/shepherd has been updated.
Fixes #
testCaseID=235 failed on GH action, but tested it locally after fixing it in [f4dd5e0](https://github.com/rancher/hosted-providers-e2e/pull/168/commits/f4dd5e0ffc8637694c67339e56691cb3cf774e9b) and it passes.
<details><summary>Details</summary>
<p>
```
Will run 1 of 33 specs
time="2024-09-19T16:38:50+05:30" level=info msg="Creating Secret(cc-rqq7d)"
time="2024-09-19T16:38:55+05:30" level=info msg="Secret(cc-rqq7d) is active"
SSSStime="2024-09-19T16:39:51+05:30" level=info msg="Cluster status is active!"
Deleting AKS resource group which will delete cluster too ...
Running command: az [group delete --name auto-aks-pvala-hp-ci-mvhkm --yes --subscription …
```
> Automate AKS Qase: 290, 235, 260,289, 199, 207, 198, 202, 217, 204

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
1. Automates Qase  222, 210, 261, 209, 217, 195, 230
2. Modifies `AddNodePool` to include all the fields wrt r/shepherd update.
Fixes #
> Automate Qase 222, 210, 261, 209, 217, 195, 230

- go.mod
- go.sum
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
* shepherd bump needed for setting k8s version on EKS nodegroup
* implemented Qase 127 - testcase for setting different k8s versions on cp and ng
* fixes for Qase 126 and 255 - in both cases error messages changed
> Bump shepherd and Automate Qase 127 (+fixes for 126 and 255)

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
OpenSUSE 15.6 updated by using `zypper ref && zypper up` - it brought new `azure-cli-2.58.0`
> Update GCP template mainly for updated azure-cli package

- .github/workflows/main.yaml
There was about 8000 Managed Secrets on GCP created by various GCP runners which costs money. 
* This PR will set Expiration time by `--ttl=18000s` for newly created secrets so they will be auto removed after 5h.
* Added line for deleting GH_REPO_ secret which was missing
> Set expiration time for GCP runner secrets

- hosted/aks/helper/helper_cluster.go
After bumping `azure-cli` on our runner template I noticed that there is a problem with creating ssh keys via `az aks create ... --generate-ssh-keys` command. 
I believe the problem is concurrency when ginkgo is trying to provision two clusters in parallel and then two `az aks create` commands are trying to write a new SSH keypair at the same time which leads to this error in CI:
~So trying to add a random sleep <0-2s> to prevent this.~ Final solution is to replace `--generate-ssh-key` by `--no-ssh-key` flag as we don't need SSH access to nodes.
> Don't use SSH for AKS nodes

- .github/workflows/main.yaml
- go.sum
* Removes outdated shepherd dependency
* Fixes go cache issue with `actions/setup-go`:
Problem is that `actions/setup-go` is confused when it sees `go 1.22.0` and `toolchain 1.22.7` in go.mod. 
The action first prepares environment for 1.22.0 (go) and then trying to override it by cached dependencies using go toolchain version 1.22.7.
By introducing this workaround we will simply install requested `go 1.22.0` (the version from go.mod) and the rest for dependencies ?should be? processed automatically within a build time.
Since `toolchain` keyword was introduced in go.mod our actions are returning errors like:
> Fix cache for actions/setup-go

- .github/workflows/janitor.yaml
The current query lists Node resource groups along with parent AKS resource groups. eg. `MC_auto-aks-hp-ci-hfzlv_auto-aks-hp-ci-hfzlv_centralindia`
This change lists only AKS resource groups since Node resource groups get auto-deleted along with them.
Unfixed run: https://github.com/rancher/hosted-providers-e2e/actions/runs/11287010203/job/31392235896#step:3:13
Fixed run: https://github.com/rancher/hosted-providers-e2e/actions/runs/11287948455/job/31394785232
> Fix az janitor query

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- Makefile
- With increased VPC limit and janitor fixes, it would be feasible to run SyncImport tests and EKS tests in parallel nodes.
- Bump local cluster k8s version to highest supported with respect to v2.9
EKS: https://github.com/rancher/hosted-providers-e2e/actions/runs/11288636844
AKS: https://github.com/rancher/hosted-providers-e2e/actions/runs/11288917687/job/31397718461#step:24:193
GKE: https://github.com/rancher/hosted-providers-e2e/actions/runs/11288537289/job/31396539524#step:24:173
Collect logs job failure to be triaged separately.
> Run Sync and EKS tests in parallel nodes and Bump k8s version

- Makefile
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
Made changes to run P1 Provisioning tests in parallel nodes so it completes execution within suite timeout.
[AKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/11538406232), [EKS](https://github.com/rancher/hosted-providers-e2e/actions/runs/11456865282), [GKE](https://github.com/rancher/hosted-providers-e2e/actions/runs/11460218371)
Above jobs are run on non-nightly build as `eks-operator/pull/876` is not yet ported to `main`
> Run P1Prov in parallel nodes

- hosted/eks/p1/p1_provisioning_test.go
Should fix this issue on EKS p1_provisioning in CI - now it will accept both AMIs for GPU enabled Nodepools (the change is present in `2.10` and `main` only)
* https://github.com/rancher/hosted-providers-e2e/actions/runs/12232378796/job/34126770946#step:17:290
> Adapt used AMI for GPU enabled nodepool in EKS

- hosted/eks/helper/helper_cluster.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
Backport of #200 and #214 
We would like to check EKS AMI when GPU is enabled, also other tests from original PR#200 were backported
> [Backport-2.10] Automate Qase 274, 94, 97, 99, 143, 145, 107, 105 & Adapt used AMI for GPU enabled nodepool in EKS

- .github/workflows/main.yaml
- .github/workflows/release-matrix.yaml
- install_test.go
Backports of:
#216 Release matrix testing all operators at once
#217 More matrix stuff
#219 Allow usage of self hosted rancher
> [release/v2.9] Release matrix and existing rancher enablement

- hosted/helpers/helper_common.go
Whenever a test times out at `WaitUntilClusterIsReady`, it returns a nil cluster, due to which the cluster is not deleted. This PR should fix this.
```
------------------------------
• [FAILED] [1800.626 seconds]
P0Provisioning when a cluster is created [BeforeEach] should successfully provision the regional cluster & add, delete, scale nodepool
[BeforeEach] /home/gh-runner/actions-runner/_work/hosted-providers-e2e/hosted-providers-e2e/hosted/gke/p0/p0_provisioning_test.go:68
[It] /home/gh-runner/actions-runner/_work/hosted-providers-e2e/hosted-providers-e2e/hosted/gke/p0/p0_provisioning_test.go:96
Captured StdOut/StdErr Output >>
Skipping downstream cluster deletion:  auto-gke-hp-ci-hzloh
<< Captured StdOut/StdErr Output
Timeline >>
"level"=0 "msg"="Using K8s version 1.31.3-gke.1162000 …
```
> Fix: Cluster deletion is skipped if timeout happens in WaitUntilClusterIsReady

- hosted/aks/helper/helper_cluster.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- Fix test case ID from 217 to 214 and fix the test.
- Add a new function CreateAKSRGOnAzure to create RG via CLI
- Increase timeout for a failing test
Fixes #192
> Fix AKS failure

- install_test.go
Switching to new nightly operator (charts and images) location from ttl.sh -> ghcr.io
ttl.sh can be used by anybody anonymously even for pushing artifacts, Yiannis decided to use secure ghcr.io. The charts and images should be still building and available from ttl.sh but we should abandon it.
> Use nightly artifacts from ghcr.io instead of ttl.sh

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/main.yaml
- .github/workflows/release-matrix.yaml
Mainly borrowed from https://github.com/rancher/rancher-turtles-e2e/pull/60
Brings new input field for github actions where you can enter auto (default), none or existing_qase_run_id.
`auto` ... uses next available qase_run_id
`none` ... no report created (default)
`run_id` ... overrides existing qase test run report
Fixes #121 
Testruns:
https://github.com/rancher/hosted-providers-e2e/actions/runs/12912527860 for `auto`
https://github.com/rancher/hosted-providers-e2e/actions/runs/12912553702 for `none (and cancelled)`
https://github.com/rancher/hosted-providers-e2e/actions/runs/12912539030 for `existing_id=1884`
https://github.com/rancher/hosted-providers-e2e/actions/runs/12912547755 for `existing_id=1871 (and cancelled)`
> Qase reporting improvements

- hosted/eks/helper/helper_cluster.go
- hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
> Automate Qase 153, 151, and 87

- hosted/eks/helper/helper_cluster.go
- hosted/helpers/helper_common.go
- This PR modifies `ListEKSAllVersions` to use a static version list in the same way the UI team does.
- `ListEKSAvailableVersions` has also been modified to use local `ListEKSAllVersions`.
- Add `GetRancherServerVersion` function to fetch the rancher server version via rancher API endpoint `/v3/settings`.
Fixes #
- [latest/devel/head P0 Prov k8sVersion: 1.30, upgradeK8sVersion: 1.31 (highest UI supported version) :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13070673133)
- [latest/2.9.3 P0 Prov](https://github.com/rancher/hosted-providers-e2e/actions/runs/13070681264)
- [latest/devel/2.10 P0 Prov :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13070691743)
> Use static EKS versions

- .github/workflows/main.yaml
- hosted/aks/helper/helper_cluster.go
- hosted/aks/p0/p0_import_test.go
- hosted/aks/p0/p0_provisioning_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- hosted/aks/p1/sync_import_test.go
- hosted/aks/p1/sync_provisioning_test.go
- hosted/eks/p0/p0_import_test.go
- hosted/eks/p0/p0_provisioning_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/eks/p1/sync_importing_test.go
- hosted/eks/p1/sync_provisioning_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/p0/p0_import_test.go
- hosted/gke/p0/p0_provisioning_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/p1_provisioning_test.go
- hosted/gke/p1/p1_suite_test.go
- hosted/gke/p1/sync_import_test.go
- hosted/gke/p1/sync_provisioning_test.go
- hosted/helpers/helper_common.go
- hosted/helpers/structs.go
- Refactor main branch to run tests on multiple Rancher versions
- Fixes P1 tests for the above and setting `cluster = nil` in `BeforeEach` 
- Skip upgrade tests for v2.8
Fixes #243 
v2.9: 
[p1_provisioning/p1_import](https://github.com/rancher/hosted-providers-e2e/actions/runs/13101626288)
[p0_provisioning/p0_import/support_matrix_provisioning/support_matrix_import/sync_provisioning/sync_import](https://github.com/rancher/hosted-providers-e2e/actions/runs/13105919092)
Re-run of failed tests: [AKS P1](https://github.com/rancher/hosted-providers-e2e/actions/runs/13133526653), [EKS SyncImport](https://github.com/rancher/hosted-providers-e2e/actions/runs/13137326697), [GKE Sync](https://github.com/rancher/hosted-providers-e2e/actions/runs/13154165694)
v2.10: …
> Refactor main branch to run tests on multiple Rancher versions

- go.mod
- go.sum
- hosted/aks/backup_restore/backup_restore_suite_test.go
- hosted/aks/helper/helper_cluster.go
- hosted/aks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/aks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/aks/p0/p0_suite_test.go
- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/aks/p1/p1_suite_test.go
- hosted/aks/p1/sync_import_test.go
- hosted/aks/p1/sync_provisioning_test.go
- hosted/eks/backup_restore/backup_restore_suite_test.go
- hosted/eks/helper/helper_cluster.go
- hosted/eks/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/eks/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/eks/p0/p0_suite_test.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_suite_test.go
- hosted/gke/backup_restore/backup_restore_suite_test.go
- hosted/gke/helper/helper_cluster.go
- hosted/gke/k8s_chart_support/k8s_chart_support_suite_test.go
- hosted/gke/k8s_chart_support/upgrade/k8s_chart_support_upgrade_suite_test.go
- hosted/gke/p0/p0_suite_test.go
- hosted/gke/p1/p1_import_test.go
- hosted/gke/p1/p1_provisioning_test.go
- hosted/gke/p1/p1_suite_test.go
This PR upgrades r/shepherd which has breaking changes, so it also adds fixes.
Fixes #
- [P0 All :green_circle: except GKE Import ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13110476323)
- [P1](https://github.com/rancher/hosted-providers-e2e/actions/runs/13112324904), [P1 GKE :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13120743928), [P1 AKS failed tests from the first run :green_circle:](https://github.com/rancher/hosted-providers-e2e/actions/runs/13130651287/job/36634972571), [P1 EKS import failed tests from first run :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13130645654/job/36634952053)
- [Sync :green_circle: ](https://github.com/rancher/hosted-providers-e2e/actions/runs/13154142147)
- [K8s Chart …
> Upgrade Shepherd and changes-post upgrade

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/k8s-chart-upgrade-matrix.yaml
- .github/workflows/release-matrix.yaml
**This PR bumps the version of local cluster to latest supported version (v1.31.5+k3s1).**
Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged): None.
> local k3s cluster version bump

- go.mod
- go.sum
This will allow to pull rancher from new stgregistry location when using `RANCHER_VERSION=latest/devel/2.10`
UPDATE 250424: https://github.com/rancher/hosted-providers-e2e/actions/runs/14639800722
[ele-testhelpers PR](https://github.com/rancher-sandbox/ele-testhelpers/pull/71)
> Bump ele-testhelpers to use stgregistry for v2.10-head

- hosted/helpers/helper_charts.go
- hosted/helpers/helper_common.go
The problem comes from [here](https://github.com/rancher/hosted-providers-e2e/blob/main/hosted/helpers/helper_common.go#L314-L324):
// HighestK8sMinorVersionSupportedByUI returns the highest k8s version supported by UI
// TODO(pvala): Use this by default when fetching a list of k8s version for all the downstream providers.
func HighestK8sMinorVersionSupportedByUI(client *rancher.Client) (value string) {
uiValue, err := client.Management.Setting.ByID("ui-k8s-default-version-range")
Expect(err).To(BeNil())
value = uiValue.Value
Expect(value).ToNot(BeEmpty())
value = strings.TrimPrefix(value, "<=v")
value = strings.TrimSuffix(value, ".x")
return value
}
The value returned by this is `<=1.14`, which is the default value of the setting ui-k8s-default-version-range if no value is set for it, …
> Fix test failures; use 'ui-k8s-supported-versions-range' instead of "ui-k8s-default-version-range" to fetch the highest UI supported k8s version

- hosted/aks/p1/p1_import_test.go
- hosted/aks/p1/p1_provisioning_test.go
- hosted/eks/p1/p1_import_test.go
- hosted/eks/p1/p1_provisioning_test.go
- The testCaseID 240 was blocked due to https://github.com/rancher/rancher/issues/43772; this bug has now been fixed on 2.12; since it won't be backported to previous versions, the test will be skipped for version < 2.12.
- Other tests (except caseID: 222, 151, and 148) that are no longer blocked by an issue have also been unblocked.
Fixes #
> Unblock previously blocked tests

- .github/workflows/aks.yaml
- .github/workflows/eks.yaml
- .github/workflows/gke.yaml
- .github/workflows/k8s-chart-upgrade-matrix.yaml
- .github/workflows/release-matrix.yaml
- go.mod
- go.sum
ref. https://github.com/rancher-sandbox/ele-testhelpers/pull/72
bump of testhelpers to support new "official" head repos & RANCHER_VERSION env updated in workflows
> Bump testhelpers to support new rancher head repos
